

services:
  service1:
    build: ./service1
    container_name: service1
    ports:
      - "8000:8000"
    volumes:
      - ./log:/app/log
    depends_on:
      - promtail

  service2:
    build: ./service2
    container_name: service2
    ports:
      - "8001:8001"
    volumes:
      - ./log:/app/log
    depends_on:
      - promtail

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    command: -config.file=/etc/promtail/config.yaml
    volumes:
      - ./promtail/config.yaml:/etc/promtail/config.yaml
      - ./log:/app/log




