server:
  http_listen_port: 0
  grpc_listen_port: 0
        
positions:
  filename: /tmp/positions.yaml
        
client:
  url: https://978006:glc_eyJvIjoiMTIwNTA2NCIsIm4iOiJzdGFjay0xMDIwMjI2LWludGVncmF0aW9uLXRva2VuIiwiayI6IkhoOWN2NjB1czA2cmI2QXlwazQyUzFSNiIsIm0iOnsiciI6InByb2QtdXMtZWFzdC0wIn19@logs-prod-006.grafana.net/api/prom/push
        
scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /app/log/*.log
